# Archivo makefile

# Proyecto 1 - Sistemas Operativos
# Ricardo Churion, carnet:11-10200
# Douglas Torres, carnet:11-11027

friendfindh: friendfindh.o
      :gcc friendfindh.o -o friendfindh

friendfindh.o: friendfindh.c friendfindh.h funcionesh.h
      :gcc -c friendfindh.c